export const ROLE = {
  USER: 'user',
  ADMIN: 'admin',
  COMPANY: 'company',
};

export const FIREARMS_TYPE = {
  PISTOL: 'pistol',
  RIFLE: 'rifle',
  SHOTGUN: 'shotgun',
  REVOLVER: 'revolver',
  CARBINE: 'carbine',
  SUBMACHINE_GUN: 'submachine gun',
  SNIPER_RIFLE: 'sniper rifle',
  MACHINE_GUN: 'machine gun',
  BOLT_ACTION: 'bolt action',
  SEMI_AUTOMATIC: 'semi-automatic',
  AUTOMATIC: 'automatic',
  LEVER_ACTION: 'lever action',
  PUMP_ACTION: 'pump action',
  DERRINGER: 'derringer',
  MUZZLELOADER: 'muzzleloader',
  COMPACT: 'compact',
  HEAVY: 'heavy',
  CUSTOM: 'custom',
  PROTOTYPE: 'prototype',
  SPORTING: 'sporting',
};

export const FIREARMS_CALIBER = {
  9: '9mm',
  40: '40',
  45: '45',
  556: '556',
  762: '762',
  12: '12g',
  20: '20g',
  308: '308',
  22: '22LR',
  380: '380',
  3006: '30-06',
  338: '338',
  10: '10mm',
  50: '50 BMG',
  243: '243',
  270: '270',
  357: '357',
  44: '44 Magnum',
  410: '410',
  28: '28g',
};

export const FIREARMS_MODEL = {
  CENTERFIRE: 'centerfire',
  RIMFIRE: 'rimfire',
  HANDGUN: 'handgun',
  SHOTGUN: 'shotgun',
  TACTICAL: 'tactical',
  SPORT: 'sport',
  LONG_RANGE: 'long range',
  HUNTING: 'hunting',
  MILITARY: 'military',
  DEFENSE: 'defense',
  POLICE: 'police',
  PRECISION: 'precision',
  CONCEALED_CARRY: 'concealed carry',
  CUSTOM: 'custom',
  LIMITED_EDITION: 'limited edition',
  ULTRALIGHT: 'ultralight',
  ALL_WEATHER: 'all weather',
  MODULAR: 'modular',
  ENTRY_LEVEL: 'entry level',
  YOUTH: 'youth',
};

export const FIREARMS_MANUFACTURER = {
  SMITH_WESSON: 'Smith & Wesson',
  GLOCK: 'Glock',
  SIG_SAUER: 'SIG Sauer',
  COLT: 'Colt',
  BERETTA: 'Beretta',
  SPRINGFIELD: 'Springfield Armory',
  CZ: 'CZ',
  BROWNING: 'Browning',
  WINCHESTER: 'Winchester',
  RUGER: 'Ruger',
  REMINGTON: 'Remington',
  HK: 'Heckler & Koch',
  FN: 'FN Herstal',
  BENELLI: 'Benelli',
  MOSSBERG: 'Mossberg',
  KIMBER: 'Kimber',
  TAURUS: 'Taurus',
  WALTHER: 'Walther',
  MARLIN: 'Marlin',
  BARRETT: 'Barrett',
};
