export const ROLE = {
  USER: 'user',
  ADMIN: 'admin',
  COMPANY: 'company',
};

export const FIREARMS_TYPE = {
  PISTOL: 'Pistol',
  RIFLE: 'Rifle',
  SHOTGUN: 'Shotgun',
  REVOLVER: 'Revolver',
  CARBINE: 'Carbine',
  SUBMACHINE_GUN: 'Submachine Gun',
  SNIPER_RIFLE: 'Sniper Rifle',
  MACHINE_GUN: 'Machine Gun',
  BOLT_ACTION: 'Bolt Action',
  SEMI_AUTOMATIC: 'Semi-Automatic',
  AUTOMATIC: 'Automatic',
  LEVER_ACTION: 'Lever Action',
  PUMP_ACTION: 'Pump Action',
  DERRINGER: 'Derringer',
  MUZZLELOADER: 'Muzzleloader',
  COMPACT: 'Compact',
  HEAVY: 'Heavy',
  CUSTOM: 'Custom',
  PROTOTYPE: 'Prototype',
  SPORTING: 'Sporting',
};

export const FIREARMS_CALIBER = {
  '9mm': '9mm',
  40: '40',
  45: '45',
  556: '556',
  762: '762',
  '12g': '12g',
  '20g': '20g',
  308: '308',
  22: '22LR',
  380: '380',
  3006: '30-06',
  338: '338',
  '10mm': '10mm',
  '50bmg': '50 BMG',
  243: '243',
  270: '270',
  357: '357',
  44: '44 Magnum',
  410: '410',
  '28g': '28g',
};

export const FIREARMS_MODEL = {
  CENTERFIRE: 'Centerfire',
  RIMFIRE: 'Rimfire',
  HANDGUN: 'Handgun',
  SHOTGUN: 'Shotgun',
  TACTICAL: 'Tactical',
  SPORT: 'Sport',
  LONG_RANGE: 'Long Range',
  HUNTING: 'Hunting',
  MILITARY: 'Military',
  DEFENSE: 'Defense',
  POLICE: 'Police',
  PRECISION: 'Precision',
  CONCEALED_CARRY: 'Concealed Carry',
  CUSTOM: 'Custom',
  LIMITED_EDITION: 'Limited Edition',
  ULTRALIGHT: 'Ultralight',
  ALL_WEATHER: 'All Weather',
  MODULAR: 'Modular',
  ENTRY_LEVEL: 'Entry Level',
  YOUTH: 'Youth',
};

export const FIREARMS_MANUFACTURER = {
  SMITH_WESSON: 'Smith & Wesson',
  GLOCK: 'Glock',
  SIG_SAUER: 'SIG Sauer',
  COLT: 'Colt',
  BERETTA: 'Beretta',
  SPRINGFIELD: 'Springfield Armory',
  CZ: 'CZ',
  BROWNING: 'Browning',
  WINCHESTER: 'Winchester',
  RUGER: 'Ruger',
  REMINGTON: 'Remington',
  HK: 'Heckler & Koch',
  FN: 'FN Herstal',
  BENELLI: 'Benelli',
  MOSSBERG: 'Mossberg',
  KIMBER: 'Kimber',
  TAURUS: 'Taurus',
  WALTHER: 'Walther',
  MARLIN: 'Marlin',
  BARRETT: 'Barrett',
};
